name: assign-issue-to-pr-author
  
runs:
  using: "composite"
  steps:
    - name: Extract Jira key and PR author from pull request
      shell: pwsh
      run: |
        JIRA_KEY=$(echo "${{ github.event.pull_request.body }}" | grep -oP '\[\K[^\]]+')
        PR_AUTHOR=${{ github.event.pull_request.user.login }}   
    - name: Setup Scripts
      shell: pwsh
      run: |
        "${{ github.action_path }}" >> $Env:GITHUB_PATH
        (Resolve-Path "${{ github.action_path }}/../../../Scripts").Path >> $Env:GITHUB_PATH

    - name: Assign issue to Pull Request Author
      shell: pwsh
      run: |
        $params = @{
            IssueQuery = "${{ env.JIRA_KEY }} in:title"
            Assignee = "${{ env.PR_AUTHOR }}"
            GitHubRepository = $Env:GITHUB_REPOSITORY
            PullRequestID = ${{ github.event.number }}
        }
        AssignIssueToPullRequestAuthor @params