name: "Prefix PR"
inputs:
  GITHUB_TOKEN:
    required: true

runs:
  using: "composite"
  steps:
    - name: Prefix PR
      shell: pwsh
      run: ${{ github.action_path }}/Prefix-PR $Env:GITHUB_REPOSITORY $Env:GITHUB_REF $Env:GITHUB_ACTION_REF ${{ inputs.GITHUB_TOKEN }}
