name: "Prefix PR"
inputs:
  GITHUB_TOKEN:
    required: true

runs:
  using: "composite"
  steps:
    - name: Prefix PR
      shell: pwsh
      run: ${{ github.action_path }}/Prefix-PR ${{ github.GITHUB_REPOSITORY }} ${{ github.GITHUB_REF }} ${{ inputs.GITHUB_TOKEN }}
