name: Login to Azure
description: Logs in to Azure using a service principal.

inputs:
  enable-azure-powershell-session:
    required: false
    default: "true"
    description: Whether to enable an Az PowerShell session.
  service-principal:
    required: true
    description: The Azure service principal credentials.

runs:
  using: "composite"
  steps:
    - name: Login to Azure
      # v1.4.6
      uses: azure/login@92a5484dfaf04ca78a94597f4f19fea633851fa2
      with:
        creds: ${{ inputs.service-principal }}
        enable-AzPSSession: ${{ inputs.enable-azure-powershell-session }}
