name: Checkout
description: >
  Runs actions/checkout. Only to centralize which version we use from the action. Intentionally not documented in
  Actions.md since it's meant to be only for internal use.

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3.1.0
      with:
        submodules: 'recursive'
