name: Create Jira issues for community activities
description: >
  Creates Jira issues for community activities happening on GitHub, like issues, discussions, pull requests being
  opened.

runs:
  using: "composite"
  steps:
    - name: Setup Scripts
      shell: pwsh
      run: |
        "${{ github.action_path }}" >> $Env:GITHUB_PATH

    - shell: pwsh
      run: |
        echo "${{ github.event.issue.body }}"

    - name: Handle Discussions
      if: github.event.discussion
      shell: pwsh
      run: |
        echo A discussion was opened.

    - name: Handle Issues
      if: github.event.issue
      shell: pwsh
      run: |
        echo An issue was opened.

    - name: Handle Pull Requests
      if: github.event.pull_request
      shell: pwsh
      run: |
        echo A pull request was opened.
