name: Create Jira issues for community activities
description: >
  Creates Jira issues for community activities happening on GitHub, like issues, discussions, pull requests being
  opened.

inputs:
  issue-component:
    required: false
    description: Optional component of the issues being created.

runs:
  using: "composite"
  steps:
    - name: Setup Scripts
      shell: pwsh
      run: |
        "${{ github.action_path }}" >> $Env:GITHUB_PATH

    - name: Login to Jira
      # v1.0.0.
      # This will show a "Logged in as: undefined" message if the login works, see:
      # https://github.com/atlassian/gajira-login/issues/30.
      uses: atlassian/gajira-login@90a599561baaf8c05b080645ed73db7391c246ed
      env:
        JIRA_BASE_URL: ${{ env.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ env.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ env.JIRA_API_TOKEN }}

    - name: Initialize Jira Issue Details
      id: issue-details
      shell: pwsh
      run: |
        # The funny indentation is necessary for here-strings.
        $github = @"
        ${{ toJSON(github) }}
        "@ | ConvertFrom-Json

        Initialize-IssueDetails $github

        $fields = @"
        {"labels": ["created-from-github"]
        "@

        if ("${{ inputs.issue-component}}" -ne "")
        {
            $fields += ', "components": [{"name": "${{ inputs.issue-component }}"}]'
        }

        $fields += '}'

        Write-Output "::set-output name=fields::$fields"

    - name: Create Jira Issue
      id: create-issue
      uses: atlassian/gajira-create@c0a9c69ac9d6aa063fed57201e55336ada860183
      with:
        project: ${{ env.JIRA_PROJECT_KEY }}
        issuetype: ${{ steps.issue-details.outputs.type }}
        summary: ${{ steps.issue-details.outputs.summary }}
        # Remote links (issue-level web links) can't be added directly when creating an issue via the API, but need to
        # be added via a separate API
        # (https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issue-remote-links/#api-rest-api-3-issue-issueidorkey-remotelink-post).
        # To simplify creating issues here, we pass the link as a magic string, which is then handled in Jira by a
        # JMWE action.
        description: ${{ steps.issue-details.outputs.link }}°ˇ^${{ fromJSON(steps.issue-details.outputs.jsonDescription) }}
        fields: ${{ steps.issue-details.outputs.fields }}

    - name: Update GitHub Issue
      if: github.event.issue
      # v3.3.0
      uses: actions-cool/issues-helper@dad28fdb88da5f082c04659b7373d85790f9b135
      with:
        actions: "update-issue"
        token: ${{ env.GITHUB_TOKEN }}
        issue-number: ${{ github.event.issue.number }}
        title: ${{ github.event.issue.title }} (${{ steps.create-issue.outputs.issue }})
        body: |
          [Jira issue](${{ env.JIRA_BASE_URL }}browse/${{ steps.create-issue.outputs.issue }})
        update-mode: 'append'
