name: Create Jira issues for community activities
description: >
  Creates Jira issues for community activities happening on GitHub, like issues, discussions, pull requests being
  opened.

inputs:
  issue-component:
    required: false
    description: Optional component of the issues being created.

runs:
  using: "composite"
  steps:
    - name: Setup Scripts
      shell: pwsh
      run: |
        "${{ github.action_path }}" >> $Env:GITHUB_PATH

    - name: Login to Jira
      # v1.0.0.
      # This will show a "Logged in as: undefined" message if the login works, see:
      # https://github.com/atlassian/gajira-login/issues/30.
      uses: atlassian/gajira-login@90a599561baaf8c05b080645ed73db7391c246ed
      env:
        JIRA_BASE_URL: ${{ env.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ env.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ env.JIRA_API_TOKEN }}

    - name: Initialize Issue Details
      id: issue-details
      shell: pwsh
      run: |
        # The funny indentation is necessary for here-strings.
        $github = @"
        ${{ toJSON(github) }}
        "@ | ConvertFrom-Json

        Initialize-IssueDetails $github

        $fields = '{"labels": ["created-from-github"]'
        if (${{ inputs.issue-component != ''}})
        {
            $fields += ', "components": [{"name": "${{ inputs.issue-component }}"}]'
        }
        $fields += '}'

        Write-Output "::set-output name=fields::'$fields'"

    - name: Create Jira issue
      id: create-issue
      uses: atlassian/gajira-create@c0a9c69ac9d6aa063fed57201e55336ada860183
      with:
        project: OSOE
        issuetype: ${{ steps.issue-details.outputs.type }}
        summary: ${{ steps.issue-details.outputs.summary }}
        description: ${{ fromJSON(steps.issue-details.outputs.jsonDescription) }}

    - name: Update Issue
      if: github.event.issue
      # v3.3.0
      uses: actions-cool/issues-helper@dad28fdb88da5f082c04659b7373d85790f9b135
      with:
        actions: "update-issue"
        token: ${{ env.GITHUB_TOKEN }}
        issue-number: ${{ github.event.issue.number }}
        title: ${{ github.event.issue.title }} (${{ steps.create-issue.outputs.issue }})
        body: |
          [Jira issue](${{ env.JIRA_BASE_URL }}browse/${{ steps.create-issue.outputs.issue }})
        update-mode: 'append'
