name: .NET Build with Static Code Analysis
description: Builds all .NET solutions in the given directory with static code analysis.

inputs:
  directory:
    required: false
    default: .
    description: Path to the directory where a solution file can be found.
  verbosity:
    required: false
    default: quiet
    description: Verbosity parameter for dotnet build.
  enable-code-analysis:
    required: false
    default: "true"
    description: If set to "true", static code analysis is enabled during the build.
  cache-packages:
    required: false
    default: "true"
    description: >
      If set to "true", the NuGet packages will be cached by GitHub. This is faster if you have a lot of NuGet packages,
      but negligible or even slower if you only have a handful. In this case disable it by setting the input to "false".

runs:
  using: "composite"
  steps:
    - name: Info build-dotnet/action.yml
      run: |
        echo "issue/OSOE-142: build-dotnet/action.yml"

    - name: Cache NuGet
      uses: actions/cache@v3
      if: ${{ inputs.cache-packages == 'true' }}
      with:
        path: ~/.nuget/packages
        key: ${{ github.repository }}-${{ runner.os }}-${{ inputs.directory }}-nuget-${{ hashFiles('**/*.nuspec') }}
        restore-keys: |
          ${{ github.repository }}-${{ runner.os }}-${{ inputs.directory }}-nuget

    - name: Build and Static Code Analysis
      shell: pwsh
      working-directory: ${{ inputs.directory }}
      run: |
        $switches = @{
            Verbosity = "${{ inputs.verbosity }}"
            EnableCodeAnalysis = "${{ inputs.enable-code-analysis }}"
            Version = "1.$Env:GITHUB_RUN_NUMBER.$Env:GITHUB_RUN_ATTEMPT-$Env:GITHUB_RUN_ID"
        }

        ${{ github.action_path }}/build.ps1 @switches
