name: .NET Build with Static Code Analysis
description: Builds all .NET solutions in the given directory with static code analysis.

inputs:
  directory:
    required: false
    default: .
    description: Path to the directory where a solution file can be found. Defaults to ".".
  verbosity:
    required: false
    default: quiet
    description: Verbosity parameter for dotnet build. Defaults to "quiet".
  enable-code-analysis:
    required: false
    default: "true"
    description: Indicates whether to enable static code analysis during build. Defaults to "true".

runs:
  using: "composite"
  steps:
    - name: Build and Static Code Analysis
      shell: pwsh
      working-directory: ${{ inputs.directory }}
      run: |
        echo "v1 1.$Env:GITHUB_RUN_NUMBER.$Env:GITHUB_RUN_ATTEMPT"
        echo "v2 1.0.0-$Env:GITHUB_RUN_ID"
        ${{ github.action_path }}/build.ps1 -Verbosity ${{ inputs.verbosity }} -EnableCodeAnalysis ${{ inputs.enable-code-analysis }} -Version "1.0.0-$Env:GITHUB_RUN_ID"
