name: Cancel Workflow
description: >
  Cancels the current workflow run, i.e. all jobs. Useful if you want to cancel the rest of the workflow when one job
  fails.

runs:
  using: "composite"
  steps:
    # Only JavaScript actions can contain post-scripts. So either that, or we use this action.
    - name: Cancel Workflow
      # Fork PRs won't have a token with write access to Actions, thus won't be able to cancel the workflow.
      if: github.event.pull_request == '' || github.event.pull_request.head.repo.fork == false
      # Post-2.0.1 commit.
      uses: webiny/action-post-run@c09eade5dd0a57b254f766ff7bc3f5725ab5adb4
      with:
        run: ${{ github.action_path }}/Invoke-WorkflowCancellation.ps1 ${{ github.repository }} ${{ github.run_id }}
