name: Cancel Workflow
description: >
  Cancels the current workflow run, i.e. all jobs. Useful if you want to cancel the rest of the workflow when one job
  fails.

runs:
  using: "composite"
  steps:
    - env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      shell: bash
      run: echo "$GITHUB_CONTEXT""

    - name: Cancel Workflow
      # Fork PRs won't have a token with write access to Actions, thus won't be able to cancel the workflow.
      if: github.event.pull_request == '' || github.event.pull_request.head.repo.fork == false
      shell: pwsh
      run: |
        $url = "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/cancel"
        $headers = @{"Authorization" = "Bearer ${{ env.GITHUB_TOKEN }}"; "Accept" = "application/vnd.github+json"}
        Invoke-WebRequest $url -Headers $headers -Method Post
