name: Cancel Workflow
description: >
  Cancels the current workflow run, i.e. all jobs. Useful if you want to cancel the rest of the workflow when one job
  fails.

runs:
  # Only JavaScript actions can contain post-scripts.
  using: "node16"
  main: "main.js"
  # Fork PRs won't have a token with write access to Actions, thus won't be able to cancel the workflow.
  post-if: github.event.pull_request == '' || github.event.pull_request.head.repo.fork == false
  post: "post.js"
