name: Check For Merge Conflict
description: Checks for merge conflicts in the current pull request.

runs:
  using: "composite"
  steps:
    - name: Dump GitHub context
      shell: bash
      run: echo '${{ toJSON(github) }}'
    - name: Dump job context
      shell: bash
      run: echo '${{ toJSON(job) }}'
    - name: Dump steps context
      shell: bash
      run: echo '${{ toJSON(steps) }}'
    - name: Dump runner context
      shell: bash
      run: echo '${{ toJSON(runner) }}'
    - name: Dump strategy context
      shell: bash
      run: echo '${{ toJSON(strategy) }}'
    - name: Dump matrix context
      shell: bash
      run: echo '${{ toJSON(matrix) }}'

    # v2.2
    - name: Check User Permissions
      id: check-user-permissions
      uses: actions-cool/check-user-permission@cd622002ff25c2311d2e7fb82107c0d24be83f9b
      with:
        username: ${{ github.triggering_actor }}

    - name: Check for merge conflict
      if: steps.check-user-permissions.user-permission != 'read'
      # releases/2.x
      uses: eps1lon/actions-label-merge-conflict@b8bf8341285ec9a4567d4318ba474fee998a6919
      with:
        repoToken: ${{ env.GITHUB_TOKEN }}
        commentOnDirty: "This pull request has merge conflicts. Please resolve those before requesting a review."
        dirtyLabel: "Merge Conflict"
