name: Check For Merge Conflict
description: Checks for merge conflicts in the current pull request.

runs:
  using: "composite"
  steps:
    # v2.2
    - uses: actions-cool/check-user-permission@cd622002ff25c2311d2e7fb82107c0d24be83f9b
