name: Check Spelling
description: Checks for spelling errors in files.

inputs:
  dictionary-source-prefixes:
    description: JSON map of prefixes for dictionary urls, "cspell" is necessary
    required: false
    default: '{"cspell": "https://raw.githubusercontent.com/check-spelling/cspell-dicts/v20220427/dictionaries/","lombiq": "https://raw.githubusercontent.com/Lombiq/GitHub-Actions/issue/OSOE-158/.github/actions/check-spelling/spelling/"}'
  extra-dictionaries:
    description: Space delimited list of URLs (or `prefix:`+path) to additional word lists
    required: false
    default:
      cspell:filetypes/filetypes.txt
      cspell:django/django.txt
      cspell:aws/aws.txt
      cspell:html/html.txt
      cspell:css/css.txt
      cspell:csharp/csharp.txt
      cspell:rust/rust.txt
      cspell:npm/npm.txt
      cspell:dotnet/dotnet.txt
      cspell:scala/scala.txt
      lombiq:expect.txt
  config:
    description: Configuration directory
    required: false
    type: string
    default: .github/actions/spelling

runs:
  using: "composite"
  steps:
  - name: Check Spelling
    uses: check-spelling/check-spelling@729687234a293e0680b12ca055a02fff415da89d
    with:
      dictionary_source_prefixes: ${{ inputs.dictionary-source-prefixes }}
      extra_dictionaries: ${{ inputs.extra-dictionaries }}
      experimental_apply_changes_via_bot: 0
      suppress_push_for_open_pull_request: 1
      post_comment: 1
      spell_check_this: Lombiq/GitHub-Actions@e07c35a1ddc7ab3c7c50e82baf05f4fb46bea3fc
      debug: 1
      # config: ${{ inputs.config }}
