name: Check Spelling
description: Checks for spelling errors in files.

permissions:
  contents: read
  pull-requests: read
  actions: read
runs-on: ubuntu-latest

runs:
  using: "composite"
  steps:
  - name: copy-files
    shell: pwsh
    run: CopyConfigFiles
  - name: check-spelling
    id: spelling
    uses: check-spelling/check-spelling@v0.0.20
    with:
      extra_dictionaries:
          cspell:filetypes/filetypes.txt
          cspell:django/django.txt
          cspell:aws/aws.txt
          cspell:html/html.txt
          cspell:css/css.txt
          cspell:csharp/csharp.txt
          cspell:rust/rust.txt
          cspell:npm/npm.txt
          cspell:dotnet/dotnet.txt
          cspell:scala/scala.txt
      experimental_apply_changes_via_bot: 0
      suppress_push_for_open_pull_request: 1
      checkout: true
      spell_check_this: check-spelling/spell-check-this@v0.0.20
      post_comment: 1
