name: Check Spelling
description: Checks for spelling errors in files.

inputs:
  example-input:
    type: string
    description: 'Debug'
    required: false
permissions:
  contents: read
  pull-requests: read
  actions: read
# outputs:
#   followup: ${{ steps.spelling.outputs.followup }}
runs-on: ubuntu-latest

runs:
  using: "composite"
  steps:
  - name: check-spelling
    id: spelling
    uses: check-spelling/check-spelling@v0.0.20
    with:
      extra_dictionaries:
          cspell:filetypes/filetypes.txt
          cspell:django/django.txt
          cspell:aws/aws.txt
          cspell:html/html.txt
          cspell:css/css.txt
      experimental_apply_changes_via_bot: 0
      suppress_push_for_open_pull_request: 1
      checkout: true
      #config: spelling/configs
      spell_check_this: check-spelling/spell-check-this@v0.0.20
      post_comment: 1