name: Check Spelling
description: Checks for spelling errors in files.

inputs:
  example-input:
    type: string
    description: 'Debug'
    required: false

runs:
  using: "composite"
    steps:
      - name: Check Spelling
        uses: check-spelling/check-spelling@v0.0.20-alpha5
