name: Check Spelling
description: Checks for spelling errors in files.

inputs:
  example-input:
    type: string
    description: 'Debug'
    required: false

runs:
  using: "composite"
  permissions:
    contents: read
    pull-requests: read
    actions: read
  outputs:
    followup: ${{ steps.spelling.outputs.followup }}
  runs-on: ubuntu-latest
  steps:
  - name: check-spelling
    id: spelling
    uses: check-spelling/check-spelling@prerelease
    with:
      experimental_apply_changes_via_bot: 1
      suppress_push_for_open_pull_request: 1
      checkout: true
      spell_check_this: check-spelling/spell-check-this@prerelease
      post_comment: 0