name: Run .NET tests
description: >
  Runs .NET unit and UI tests (with the Lombiq UI Testing Toolbox for Orchard Core:
  https://github.com/Lombiq/UI-Testing-Toolbox), generates a test report and uploads UI testing failure dumps to
  artifacts.

inputs:
  build-directory:
    required: false
    default: .
    description: Path to the directory where a solution file can be found and thus the .NET build has run.
  test-verbosity:
    required: false
    default: quiet
    description: Verbosity parameter for dotnet test.
  ui-test-parallelism:
    required: false
    default: "0"
    description: >
      Determines how many UI tests will run in parallel. Affects both xUnit's maxParallelThreads configuration and the
      MaxParallelTests configuration of Lombiq UI Testing Toolbox. If set to "-1" then the configuration coming from the
      code won't be overridden.

runs:
  using: "composite"
  steps:
    - name: Set UI Test Parallelization
      shell: pwsh
      run: |
        if (${{ inputs.ui-test-parallelism }} -eq -1)
        {
            Write-Output "The UI test parallelism configuration isn't overridden.".
            Exit 0
        }

        "Lombiq_Tests_UI__OrchardCoreUITestExecutorConfiguration__MaxParallelTests=${{ inputs.ui-test-parallelism }}" >> $Env:GITHUB_ENV
        $Env:Lombiq_Tests_UI__OrchardCoreUITestExecutorConfiguration__MaxParallelTests = "${{ inputs.ui-test-parallelism }}"

        ${{ github.action_path }}/replace-xunit-maxParallelThreads.ps1 -MaxParallelThreads ${{ inputs.ui-test-parallelism }}
    
    - name: Run Tests
      shell: pwsh
      working-directory: ${{ inputs.build-directory }}
      run: |
        ${{ github.action_path }}/run-tests.ps1 -Verbosity ${{ inputs.test-verbosity }}
