name: Run .NET tests
description: >
  Runs .NET unit and UI tests (with the Lombiq UI Testing Toolbox for Orchard Core:
  https://github.com/Lombiq/UI-Testing-Toolbox), generates a test report and uploads UI testing failure dumps to
  artifacts.

inputs:
  build-directory:
    required: false
    default: .
    description: Path to the directory where a solution file can be found and thus the .NET build has run.
  test-verbosity:
    required: false
    default: quiet
    description: Verbosity parameter for dotnet test.
  ui-test-parallelism:
    required: false
    default: "0"
    description: >
      Determines how many UI tests will run in parallel. Affects both xUnit's maxParallelThreads configuration and the
      MaxParallelTests configuration of Lombiq UI Testing Toolbox.

runs:
  using: "composite"
  steps:
    - name: Set UI Test Parallelization
      shell: pwsh
      run: |
        "Lombiq_Tests_UI__OrchardCoreUITestExecutorConfiguration__MaxParallelTests=${{ inputs.ui-test-parallelism }}" >> $Env:GITHUB_ENV
        $Env:Lombiq_Tests_UI__OrchardCoreUITestExecutorConfiguration__MaxParallelTests = "${{ inputs.ui-test-parallelism }}"

        ${{ github.action_path }}/replace-xunit-maxParallelThreads.ps1 -MaxParallelThreads ${{ inputs.ui-test-parallelism }}
    
    - name: Run Tests1
      shell: pwsh
      working-directory: ${{ inputs.build-directory }}
      run: |
        ${{ github.action_path }}/run-tests.ps1 -Verbosity ${{ inputs.test-verbosity }}

    - name: Run Tests2
      shell: pwsh
      working-directory: ${{ inputs.build-directory }}
      run: |
        ${{ github.action_path }}/run-tests.ps1 -Verbosity ${{ inputs.test-verbosity }}

    - name: Run Tests3
      shell: pwsh
      working-directory: ${{ inputs.build-directory }}
      run: |
        ${{ github.action_path }}/run-tests.ps1 -Verbosity ${{ inputs.test-verbosity }}

    - name: Run Tests4
      shell: pwsh
      working-directory: ${{ inputs.build-directory }}
      run: |
        ${{ github.action_path }}/run-tests.ps1 -Verbosity ${{ inputs.test-verbosity }}

    - name: Run Tests5
      shell: pwsh
      working-directory: ${{ inputs.build-directory }}
      run: |
        ${{ github.action_path }}/run-tests.ps1 -Verbosity ${{ inputs.test-verbosity }}

    - name: Run Tests6
      shell: pwsh
      working-directory: ${{ inputs.build-directory }}
      run: |
        ${{ github.action_path }}/run-tests.ps1 -Verbosity ${{ inputs.test-verbosity }}
