name: Automatically Merge Pull Request
description: Merges the current pull request automatically if the "auto-merge-if-checks-succeed" label is present.

runs:
  using: "composite"
  steps:
    - name: Automatically Merge Pull Request
      # If this is run for a PR opened from a fork (not from a branch in the given repo) then "Resource not accessible
      # by integration" errors can happen. Thus, not running it for forks during the pull_request event (but it can
      # run during push, for example). See https://github.com/Lombiq/GitHub-Actions/issues/72 for details.
      if: github.event.pull_request.head.repo.fork == false
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      shell: bash
      run: echo "$GITHUB_CONTEXT"
