name: Automatically Merge Pull Request
description: Merges the current pull request automatically if the "auto-merge-if-checks-succeed" label is present.

runs:
  using: "composite"
  steps:
    - name: Setup Scripts
      shell: pwsh
      run: |
        "${{ github.action_path }}" >> $Env:GITHUB_PATH
        (Resolve-Path "${{ github.action_path }}/../../../Scripts").Path >> $Env:GITHUB_PATH

    - name: Check Mergeability
      id: check-mergeability
      # Fork PR runs won't have permissions to add labels to or merge PRs.
      if: github.event.pull_request.head.repo.fork == false
      shell: pwsh
      run: |
        # We need to fetch the PR details from the API as opposed to just using the context, because a label added after
        # the start of the run wouldn't be present in it.
        $url = "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}"
        $headers = @{"Authorization" = "Bearer $($Env:GITHUB_TOKEN)"; "Accept" = "application/vnd.github+json"}
        $response = Invoke-WebRequest $url -Headers $headers -Method Get
        Test-Mergeability $response

    #- name: Merge Pull Request
    #  if: steps.check-mergeability.outputs.is-mergeable == 'true'
    #  shell: pwsh
    #  run: |
    #    $url = "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/merge"
    #    $headers = @{"Authorization" = "Bearer ${{ env.GITHUB_TOKEN }}"; "Accept" = "application/vnd.github+json"}
    #    Invoke-WebRequest $url -Headers $headers -Method Put

    #- name: Remove Label
    #  if: steps.check-mergeability.outputs.is-mergeable == 'true'
    #  # v1.1.1
    #  uses: mondeja/remove-labels-gh-action@9c39e92024101ccb2473aeee441d4923adf58089
    #  with:
    #    token: ${{ env.GITHUB_TOKEN }}
    #    labels: |
    #      merge-and-resolve-jira-issue-if-checks-succeed
    #      merge-if-checks-succeed
