name: Automatically Merge Pull Request
description: Merges the current pull request automatically if the "auto-merge-if-checks-succeed" label is present.

runs:
  using: "composite"
  steps:
    #- name: Output test
    #  env:
    #    GITHUB_CONTEXT: ${{ toJSON(github) }}
    #  shell: bash
    #  run: echo "$GITHUB_CONTEXT"

    - name: Setup Scripts
      shell: pwsh
      run: |
        "${{ github.action_path }}" >> $Env:GITHUB_PATH
        (Resolve-Path "${{ github.action_path }}/../../../Scripts").Path >> $Env:GITHUB_PATH

    - name: Check Mergeability
      id: check-mergeability
      # Fork PR runs won't have permissions to add labels to or merge PRs.
      if: github.event.pull_request.head.repo.fork == false
      shell: pwsh
      run: |
        $url = "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}"
        $headers = @{"Authorization" = "Bearer ${{ env.GITHUB_TOKEN }}"; "Accept" = "application/vnd.github+json"}
        $response = Invoke-WebRequest $url -Headers $headers -Method Get
        Test-Mergeability $response

    - name: Merge Pull Request
      if: steps.check-mergeability.outputs.is-mergeable == 'true'
      shell: pwsh
      run: |
        Write-Output "This is mergeable."

