name: Set up .NET
description: Sets up the .NET SDK.

inputs:
  dotnet-version:
    required: false
    default: 6.0.*
    description: Version of the .NET SDK to set up. Defaults to 6.0.*.

runs:
  using: "composite"
  steps:
    - name: Set environment variables
      shell: pwsh
      run: |
        $Env:DOTNET_SKIP_FIRST_TIME_EXPERIENCE = "true"
        $Env:DOTNET_CLI_TELEMETRY_OPTOUT = "true"
        $Env:SOMETHING_ELSE_JUST_FOR_ME = "hehe"
    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ inputs.dotnet-version }}
