name: Set up .NET
description: Sets up the .NET SDK.

inputs:
  dotnet-version:
    required: false
    default: 6.0.*
    description: Version of the .NET SDK to set up. Defaults to 6.0.*.

runs:
  using: "composite"
  steps:
    - name: Set up .NET
      env:
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "true"
        DOTNET_CLI_TELEMETRY_OPTOUT: "true"
        SOMETHING_ELSE_JUST_FOR_ME: "hehe"
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ inputs.dotnet-version }}
