name: build

on:
  workflow_call:
    with: 
      project:
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
      - name: Install dependencies
        run: dotnet restore ${{ inputs.project }}
      - name: Build
        run: dotnet build ${{ inputs.project }} --configuration Release --no-restore
      - name: Test
        run: dotnet test ${{ inputs.project }} --no-restore
