name: build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.*
      - name: Install dependencies
        run: dotnet restore -p:NuGetBuild=True
      - name: Add package
        id: add_package
        run: |
          curl https://raw.githubusercontent.com/Lombiq/GitHub-Actions/dev/scripts/add-github-sourcelink.sh >> add-github-sourcelink.sh
          bash add-github-sourcelink.sh Microsoft.SourceLink.GitHub
          rm add-github-sourcelink.sh
      - name: Build
        run: dotnet build --configuration Release --no-restore  -p:NuGetBuild=True -p:LangVersion=Latest
