name: build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
      - name: Install dependencies
        run: dotnet restore -p:NuGetBuild=True
      - name: Build
        run: dotnet build --configuration Release --no-restore  -p:NuGetBuild=True
      - name: Test
        run: dotnet test --no-restore  -p:NuGetBuild=True
