name: Build .NET

on:
  workflow_call:
    inputs:
      # This needs to be stringified JSON because inputs don't support arrays, see 
      # https://github.community/t/reusable-workflow-with-strategy-matrix/205676/2.
      machine-types:
        required: false
        type: string
        default: "[\"ubuntu-latest\"]"
        description: >
            Stringified JSON array with the name of the type of machine(s) to run the workflow under, e.g.
            "[\"ubuntu-latest\"]" or "[\"ubuntu-latest\", \"windows-latest\"]". Defaults to "[\"ubuntu-latest\"]".
      dotnet-version:
        required: false
        type: string
        default: 6.0.*
        description: >
          Version of the .NET SDK to set up. Defaults to 6.0.*.
      build-directory:
        required: false
        type: string
        default: .
        description: Path to the directory where a solution file can be found. Defaults to ".".
      build-verbosity:
        required: false
        type: string
        default: quiet
        description: Verbosity parameter for dotnet build. Defaults to "quiet".
      build-enable-code-analysis:
        required: false
        type: string
        default: "true"
        description: Indicates whether to enable static code analysis during dotnet build. Defaults to "true".
      timeout-minutes:
        required: false
        type: number
        default: 360
        description: Configuration for the timeout-minutes parameter of the workflow. Defaults to 360 (the GitHub default).

jobs:
  call-build-and-test-workflow:
    name: Build and Test
    uses: Lombiq/GitHub-Actions/.github/workflows/build-and-test-orchard-core.yml@issue/NEST-314
    with: 
      machine-types: "[\"ubuntu-latest\"]"
      timeout-minutes: 60