name: build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.*

      - name: Install dependencies
        run: dotnet restore -p:NuGetBuild=True

      - name: Build
        run: dotnet build --configuration Release --no-restore  -p:NuGetBuild=True -p:LangVersion=Latest
