name: Check For Merge Conflict

on:
  workflow_call:
    inputs:
      token:
        required: true
        description: Github Token

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Check for Merge Conflict in PR
      uses: Lombiq/GitHub-Actions/.github/actions/check-merge-conflict@issue/OSOE-144