name: Check Spelling

on:
  workflow_call:

jobs:
  check-spelling:
    name: Check Spelling
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Copy file
        uses: canastro/copy-action@0.0.2
        with:
          source: "../spelling/excludes.txt"
          target: ".github/actions/spelling/excludes.txt"

      - name: Check Spelling
        uses: Lombiq/GitHub-Actions/.github/actions/check-spelling@issue/OSOE-158
        with:
          expamle-input: ${{ inputs.example-input }}
