name: Check Spelling

on:
  workflow_call:
    inputs:
      debug:
        type: string
        description: 'Debug'
        required: false

jobs:
  check-spelling:
    name: Check Spelling
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Check Spelling
        uses: Lombiq/GitHub-Actions/.github/actions/check-spelling@issue/OSOE-158