name: Create Jira issues for community activities

on:
  workflow_call:
    secrets:
      # We can't access org secrets here so they need to be passed in.
      JIRA_BASE_URL:
        required: true
      JIRA_USER_EMAIL:
        required: true
      JIRA_API_TOKEN:
        required: true
      DISCUSSION_JIRA_ISSUE_DESCRIPTION:
        required: true
      ISSUE_JIRA_ISSUE_DESCRIPTION:
        required: true
      PULL_REQUEST_JIRA_ISSUE_DESCRIPTION:
        required: true
    inputs:
      issue-component:
        required: false
        type: string
        description: Optional component of the issues being created.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Create Jira issues for community activities
      uses: Lombiq/GitHub-Actions/.github/actions/create-jira-issues-for-community-activities@issue/OSOE-173
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        DISCUSSION_JIRA_ISSUE_DESCRIPTION: ${{ secrets.DISCUSSION_JIRA_ISSUE_DESCRIPTION }}
        ISSUE_JIRA_ISSUE_DESCRIPTION: ${{ secrets.ISSUE_JIRA_ISSUE_DESCRIPTION }}
        PULL_REQUEST_JIRA_ISSUE_DESCRIPTION: ${{ secrets.PULL_REQUEST_JIRA_ISSUE_DESCRIPTION }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        issue-component: ${{ inputs.issue-component }}
