name: Create Jira issues for community activities

on:
  workflow_call:
    inputs:
      repo:
        required: false
        type: string
        default: Lombiq/Open-Source-Orchard-Core-Extensions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Create Jira issues for community activities
      uses: Lombiq/GitHub-Actions/.github/actions/create-jira-issues-for-community-activities@issue/OSOE-173
