name: Create Jira issues for community activities

on:
  workflow_call:
    inputs:
      repo:
        required: false
        type: string
        default: Lombiq/Open-Source-Orchard-Core-Extensions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT
