name: Deploy to Azure App Service

on:
  workflow_call:
    secrets:
      AZURE_APP_SERVICE_DEPLOYMENT_SERVICE_PRINCIPAL:
        required: true
      AZURE_APP_SERVICE_PUBLISH_PROFILE:
        required: true
    inputs:
      # This needs to be stringified JSON because inputs don't support arrays, see 
      # https://github.community/t/reusable-workflow-with-strategy-matrix/205676/2.
      machine-types:
        required: false
        type: string
        default: "[\"ubuntu-latest\"]"
        description: >
            Stringified JSON array with the name of the type of machine(s) to run the workflow under, e.g.
            "[\"ubuntu-latest\"]" or "[\"ubuntu-latest\", \"windows-latest\"]".
      dotnet-version:
        required: false
        type: string
        default: 6.0.*
        description: Version of the .NET SDK to set up.
      build-directory:
        required: false
        type: string
        default: .
        description: Path to the directory where a solution file can be found.
      build-verbosity:
        required: false
        type: string
        default: quiet
        description: Verbosity parameter for dotnet build.
      timeout-minutes:
        required: false
        type: number
        default: 360
        description: Configuration for the timeout-minutes parameter of the workflow. The 360 is GitHub's default.
      app-name:
        required: true
        type: string
        description: What you see at the top of the blade on the Azure Portal. Can contain uppercase letters too.
      slot-name:
        required: true
        type: string
        description: Also what you see at the top of the blade when you open the slot, before the app name in parenthesis.
      resource-group-name:
        required: true
        type: string
        description: Name of the resource group.
      url:
        required: true
        type: string
        description: The URL of the web app slot.
      web-project-path:
        required: false
        type: string
        default: "*.Web.csproj"
        description: >
          The path of the web project file to be processed. The value is given to PowerShell's `Get-ChildItem` cmdlet
          as-is, so grepping is still possible but a name with spaces must be escaped separately.
      runtime:
        required: false
        type: string
        description: If specified, the web app gets published using this runtime and in "ready to run" mode.

jobs:
  deploy:
    runs-on: ${{ matrix.machine-type }}
    name: Deploy to Azure App Service
    defaults:
      run:
        shell: pwsh
    # Timeout-minutes is in the matrix only because the config can't be set directly from the inputs, see:
    # https://github.com/actions/runner/issues/1555.
    strategy:
      matrix:
        machine-type: ${{ fromJson(inputs.machine-types) }}
        timeout-minutes:
        - ${{ inputs.timeout-minutes }}
    timeout-minutes: ${{ matrix.timeout-minutes }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Set up .NET
      uses: Lombiq/GitHub-Actions/.github/actions/setup-dotnet@dev
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Enable Node corepack
      uses: Lombiq/GitHub-Actions/.github/actions/enable-corepack@dev

    - name: Build and Publish
      env:
        publish-command-base: >
          dotnet publish (Get-ChildItem ${{ inputs.web-project-path }}).FullName --configuration Release
          --output '${{ inputs.build-directory }}/Published' --verbosity ${{ inputs.build-verbosity }}
      run: |
        if ([string]::IsNullOrEmpty(${{ inputs.runtime }}))
        {
          Invoke-Expression $publish-command-base
        }
        else
        {
          Invoke-Expression ($publish-command-base + " --runtime ${{ inputs.runtime }} -p:PublishReadyToRun=true --self-contained false")
        }

    - name: Login to Azure
      # v1
      uses: azure/login@24848bc889cfc0a8313c2b3e378ac0d625b9bc16
      with:
        creds: ${{ secrets.AZURE_APP_SERVICE_DEPLOYMENT_SERVICE_PRINCIPAL }}
        enable-AzPSSession: true

    - name: Stop Web App Slot
      # v1
      uses: Azure/powershell@38b0aa56c413239bd9dcc898d1f62986233658bc
      with:
        inlineScript: |
          Stop-AzWebAppSlot -ResourceGroupName ${{ inputs.resource-group-name }} -Name ${{ inputs.app-name }} -Slot ${{ inputs.slot-name }}
        azPSVersion: latest

    - name: Deploy to Azure App Service
      # v2
      uses: azure/webapps-deploy@0b651ed7546ecfc75024011f76944cb9b381ef1e
      with:
        app-name: ${{ inputs.app-name }}
        slot-name: ${{ inputs.slot-name }}
        publish-profile: ${{ secrets.AZURE_APP_SERVICE_PUBLISH_PROFILE }}
        package: ${{ inputs.build-directory }}/Published

    - name: Start Web App Slot
      # v1
      uses: Azure/powershell@38b0aa56c413239bd9dcc898d1f62986233658bc
      with:
        inlineScript: |
          Start-AzWebAppSlot -ResourceGroupName ${{ inputs.resource-group-name }} -Name ${{ inputs.app-name }} -Slot ${{ inputs.slot-name }}
        azPSVersion: latest

    - name: Ping Web App Slot
      run: curl --connect-timeout 100 --retry 3 --retry-delay 15 ${{ inputs.url }}
