name: Post Pull Request Checks Automation

on:
  workflow_call:
    secrets:
      # We can't access org secrets here so they need to be passed in.
      JIRA_BASE_URL:
        required: true
        description: >
          Configure as explained under https://github.com/marketplace/actions/jira-login#enviroment-variables. Note that
          it must NOT end with a slash.
      JIRA_USER_EMAIL:
        required: true
        description: Configure as explained under https://github.com/marketplace/actions/jira-login#enviroment-variables.
      JIRA_API_TOKEN:
        required: true
        description: Configure as explained under https://github.com/marketplace/actions/jira-login#enviroment-variables.

jobs:
  post-pull-request-checks-automation:
    runs-on: ubuntu-latest
    steps:
    - name: Automatically Merge Pull Request
      if: github.event.pull_request != ''
      uses: Lombiq/GitHub-Actions/.github/actions/auto-merge-pull-request@issue/OSOE-477
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Automatically Resolve or Done Jira issue
      if: github.event.pull_request != ''
      uses: Lombiq/GitHub-Actions/.github/actions/auto-resolve-done-jira-issue@issue/OSOE-477
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Remove Label
      # v1.1.1
      uses: mondeja/remove-labels-gh-action@9c39e92024101ccb2473aeee441d4923adf58089
      with:
        token: ${{ env.GITHUB_TOKEN }}
        labels: |
          merge-and-resolve-jira-issue-if-checks-succeed
