name: publish

on:
  workflow_call:
    inputs: 
      project:
        required: false
        type: string
      version:
        required: true
        type: string
    secrets:
      apikey:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
      - name: Install dependencies
        run: dotnet restore ${{ inputs.project }}
      - name: Build
        run: dotnet build ${{ inputs.project }} --configuration Release --no-restore
      - name: Test
        run: dotnet test ${{ inputs.project }} --no-restore
      - name: Pack
        run: dotnet pack ${{ inputs.project }} --output artifacts --configuration Release --no-restore --no-build -p:Version=${{ inputs.version }} -p:TreatWarningsAsErrors=false 
      - name: Push with dotnet
        run: dotnet nuget push artifacts/*.nupkg --api-key ${{ secrets.apikey }} --source https://nuget.cloudsmith.io/orchardcore/preview/v3/index.json --skip-duplicate
      - name: Archive artifacts
        uses: actions/upload-artifact@v1
        with:
          name: artifacts
          path: artifacts          
