name: publish

on:
  workflow_call:
    inputs: 
      source:
        required: false
        type: string
    secrets:
      # We can't access org secrets here so they need to be passed in, see:
      # https://github.community/t/resuable-called-workflow-environment-variables-secrets-and-trigger-event-access/207723/2
      API_KEY:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: haya14busa/action-cond@v1
        id: sourceeval
        with:
          cond: ${{ inputs.source == '' }}
          if_true: "https://api.nuget.org/v3/index.json"
          if_false: "${{ inputs.source }}"
      - name: Print source
        run: echo Nuget Source:${{ steps.sourceeval.outputs.value }}
      - name: Get the version
        id: get_version
        run: |
          VERSION="${GITHUB_REF_NAME//v}"
          echo VERSION:${VERSION}
          echo ::set-output name=VERSION::${VERSION}         
      - uses: actions/checkout@v2    
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.*
      - name: Install dependencies
        run: dotnet restore -p:NuGetBuild=True
      - name: Build
        # -p:GenerateDocumentationFile=True is needed both for build and pack. It'd cause a CS1591 ("Missing XML comment
        # for publicly visible type or member 'Type_or_Member'") warning but we hande that centrally from .NET Analyzers.
        run: dotnet build --configuration Release --no-restore -p:NuGetBuild=True -p:LangVersion=Latest -p:GenerateDocumentationFile=True -p:NoWarn=CS1591
      - name: Pack
        # NoWarn on NU5104 to not have warnings for prerelease dependencies, see: https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu5104.
        run: dotnet pack --output artifacts --configuration Release --no-restore --no-build  -p:NuGetBuild=True -p:Version=${{ steps.get_version.outputs.VERSION }} -p:NoWarn=NU5104 -p:TreatWarningsAsErrors=true -warnaserror -p:WarnOnPackingNonPackableProject=True -p:GenerateDocumentationFile=True
      - name: Push with dotnet
        run: dotnet nuget push artifacts/*.nupkg --api-key ${{ secrets.API_KEY }} --source ${{ steps.sourceeval.outputs.value }} --skip-duplicate
      - name: Archive artifacts
        uses: actions/upload-artifact@v1
        with:
          name: artifacts
          path: artifacts          
