name: Publish to NuGet

on:
  workflow_call:
    inputs:
      source:
        required: false
        type: string
        default: https://api.nuget.org/v3/index.json
        description: The NuGet server URL used by the `dotnet nuget push` command's `--source` argument. 
      verbosity:
        required: false
        type: string
        default: minimal
        description: The logging verbosity type used by the `dotnet` command.
    secrets:
      # We can't access org secrets here so they need to be passed in, see:
      # https://github.community/t/resuable-called-workflow-environment-variables-secrets-and-trigger-event-access/207723/2
      API_KEY:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Publish to NuGet
      uses: Lombiq/GitHub-Actions/.github/actions/publish-nuget@issue/OSOE-139
      with:
        source: ${{ inputs.source }}
        verbosity: ${{ inputs.verbosity }}
      secrets:
        API_KEY: ${{ secrets.API_KEY }}