name: Validate Pull Request

on:
  workflow_call:
    secrets:
      # We can't access org secrets here so they need to be passed in.
      JIRA_BASE_URL:
        description: >
          Configure as explained under https://github.com/marketplace/actions/jira-login#enviroment-variables. Note that
          it must NOT end with a slash.

jobs:
  validate-pull-request:
    runs-on: ubuntu-latest
    steps:
    - name: Validate Jira Issue Code in Pull Request
      if: github.event.pull_request != ''
      uses: Lombiq/GitHub-Actions/.github/actions/prefix-pr@issue/OSOE-425
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Check for Merge Conflict in PR
      uses: Lombiq/GitHub-Actions/.github/actions/check-merge-conflict@issue/OSOE-425
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
