name: Validate Pull Request

on:
  workflow_call:
  # We can't access org secrets here so they need to be passed in.    
    secrets:
      JIRA_BASE_URL:
        required: true
        description: >
          Configure as explained under https://github.com/marketplace/actions/jira-login#enviroment-variables.
          Note that it must NOT end with a slash.
    inputs:
      repo:
        required: false
        type: string
        default: Lombiq/Open-Source-Orchard-Core-Extensions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Prefix PR with issue key
      uses: Lombiq/GitHub-Actions/.github/actions/prefix-pr@issue/OSOE-425
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Ensure Parent PR Exists
      uses: Lombiq/GitHub-Actions/.github/actions/verify-submodule-pull-request@issue/OSOE-425
      with:
        title: ${{ github.event.pull_request.title }}
