name: Validate Pull Request

on:
  workflow_call:
    secrets:
      # We can't access org secrets here so they need to be passed in.
      JIRA_BASE_URL:
        required: false
        description: >
          Configure as explained under https://github.com/marketplace/actions/jira-login#enviroment-variables. Note that
          it must NOT end with a slash.

jobs:
  validate-pull-request:
    runs-on: ubuntu-22.04
    steps:
      - name: Add Jira Issue Code to Pull Request
        if: github.event_name == 'pull_request' && github.event.action == 'opened' 
        uses: Lombiq/GitHub-Actions/.github/actions/add-jira-issue-code-to-pull-request@dev
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract Jira key and PR author from pull request
        run: |
          JIRA_KEY="${{ github.event.pull_request.body }}"
          PR_AUTHOR=${{ env.PULL_REQUEST_AUTHOR_LOGIN }}

      - name: Assign issue to PR author
        uses: Lombiq/GitHub-Actions/.github/actions/assign-issue-to-pr-author@issue/OSOE-545
        env:
          ISSUE_QUERY: "${{ env.JIRA_KEY }} in:title"
          ASSIGNEE: "${{ env.PR_AUTHOR }}"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }

      - name: Check for Merge Conflict in PR
        uses: Lombiq/GitHub-Actions/.github/actions/check-merge-conflict@dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
