name: Validate Pull Request

on:
  workflow_call:

jobs:
  validate-pull-request:
    runs-on: ubuntu-latest
    steps:
    - name: Prefix PR with issue key
      uses: Lombiq/GitHub-Actions/.github/actions/prefix-pr@issue/OSOE-425
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Check for Merge Conflict in PR
      uses: Lombiq/GitHub-Actions/.github/actions/check-merge-conflict@issue/OSOE-425
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
