name: Validate Pull Request

on:
  workflow_call:

jobs:
  validate-pull-request:
    uses: Lombiq/GitHub-Actions/.github/actions/check-merge-conflict@issue/OSOE-144
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
