name: Verify Submodule Pull Request

on:
  workflow_call:
    inputs:
      repo:
        required: false
        type: string
        default: Lombiq/Open-Source-Orchard-Core-Extensions

env:
  PULL_REQUEST_TITLE: ${{ github.event.pull_request.title }}

defaults:
  run:
    shell: pwsh

jobs:
  parent-pull-request-exists:
    runs-on: ubuntu-latest
    name: Parent PR Exists
    steps:
      - name: Print PR Title
        run: echo $Env:PULL_REQUEST_TITLE

      - name: Add Commands to Subsequent Workflow Steps
        run: |
          $profileDirectory = [System.IO.Path]::GetDirectoryName($Profile)
          [System.IO.Directory]::CreateDirectory($profileDirectory)

          Write-Output "github.action_path = '${{ github.action_path }}'"
          Get-Content -Raw '${{ github.action_path }}/scripts/verify/commands.ps1' | 
              Out-File $Profile -Append

      - name: Ensure Current PR Title Includes Issue Code
        run: |
          Exit-EnsureCurrentPullRequest $Env:PULL_REQUEST_TITLE

      - name: Ensure Parent Repository Contains Matching PR
        run: |
          Exit-EnsureParentPullRequest '${{ inputs.repo }}' $Env:PULL_REQUEST_TITLE
