name: Verify Submodule Pull Request

on:
  workflow_call:
    inputs:
      repository:
        type: string
        required: false
        default: Lombiq/Open-Source-Orchard-Core-Extensions
        description: The parent repository's full name in "{owner}/{repository}" format.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Ensure Parent PR Exists
      uses: Lombiq/GitHub-Actions/.github/actions/verify-submodule-pull-request@dev
      with:
        title: ${{ github.event.pull_request.title }}
        repository: ${{ inputs.repository }}
