name: Import Reset Environment Scripts
description: Import Reset Environment Scripts

runs:
  using: "composite"
  steps:
    - name: Setup
      shell: pwsh
      run: |
        "${{ github.action_path }}" >> $Env:GITHUB_PATH

    - name: Import Scripts
      shell: pwsh
      run: |
        './*.psm1' | gci | Import-Module
        Get-Module | Write-Output
        Get-Location | Write-Output
